# Generated by Django 5.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0002_extracteddata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtractedData',
        ),
    ]