# Generated by Django 6.0 on 2026-01-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0002_extracteddata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtractedData',
        ),
    ]
